FROM    python:3.9.1

# Add a local user, switch to it and make a new WORKDIR
RUN     useradd -m -U user
USER    user
RUN     mkdir /home/user/cps-spa-detection-tool
WORKDIR /home/user/cps-spa-detection-tool
ENV     PATH="/home/user/.local/bin:$PATH"

# Install and upgrade python setup utilities
RUN     python3 -m pip install --user --upgrade pip setuptools wheel

# Install the python requirements needed at runtime
COPY    setup.py /home/user/cps-spa-detection-tool
COPY    setup.cfg /home/user/cps-spa-detection-tool
COPY    requirements.txt /home/user/cps-spa-detection-tool
RUN     pip install --user -r requirements.txt

# Copy the module and install
COPY    /dt /home/user/cps-spa-detection-tool/dt
COPY    /tests /home/user/cps-spa-detection-tool/tests
RUN     pip install --user --no-use-pep517 --editable /home/user/cps-spa-detection-tool

