FROM    python:3.9.1

RUN adduser --disabled-password --gecos '' user
USER user
RUN mkdir ~/cps-spa-detection-tool

# set work directory
WORKDIR /home/user/cps-spa-detection-tool

# Set virtual environment
ENV VIRTUAL_ENV=venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install dependencies
RUN python3 -m pip install --upgrade pip virtualenv
RUN pip install --upgrade pip setuptools wheel

# Copy files required for setting up virtual env
COPY    setup.py /home/user/cps-spa-detection-tool
COPY    setup.cfg /home/user/cps-spa-detection-tool
COPY    requirements.txt /home/user/cps-spa-detection-tool

# Copy files related to testing and reporting
COPY    pyproject.toml /home/user/cps-spa-detection-tool
COPY    build_virtual_env.sh /home/user/cps-spa-detection-tool

# Copy the module
COPY    /dt /home/user/cps-spa-detection-tool/dt
COPY    /tests /home/user/cps-spa-detection-tool/tests

RUN pip install -r requirements.txt
RUN pip install --editable /home/user/cps-spa-detection-tool
